version: '2'
services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - "./zookeeper/data:/data"
      - "./zookeeper/datalog:/datalog"
      - "./zookeeper/logs:/logs"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
     KAFKA_BROKER_ID: 0
     #KAFKA_ADVERTISED_HOST_NAME: 172.16.193.120
     #KAFKA_ADVERTISED_PORT: 9092
     KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9092,OUTSIDE://172.16.193.120:9094
     KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
     KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
     KAFKA_CREATE_TOPICS: "test2:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka:/kafka