version: '3.1'

services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2182:2181
    volumes:
      - "./node1/volumes/data:/data"
      - "./node1/volumes/datalog:/datalog"
      - "./node1/volumes/logs:/logs"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    ports:
      - 2183:2181
    volumes:
      - "./node2/volumes/data:/data"
      - "./node2/volumes/datalog:/datalog"
      - "./node2/volumes/logs:/logs"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    ports:
      - 2184:2181
    volumes:
      - "./node3/volumes/data:/data"
      - "./node3/volumes/datalog:/datalog"
      - "./node3/volumes/logs:/logs"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181